// This file is auto-generated by TanStack Router
// We create it manually here for the initial setup
// In production, use the TanStack Router CLI or Vite plugin

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRoute } from "./routes/index";
import { Route as LoginRoute } from "./routes/login";
import { Route as RegisterRoute } from "./routes/register";
import { Route as AppRoute } from "./routes/app";
import { Route as AppIndexRoute } from "./routes/app/index";
import { Route as AppCalendarRoute } from "./routes/app/calendar";
import { Route as AppSettingsRoute } from "./routes/app/settings";

// Create the route tree
const routeTree = rootRoute.addChildren([
  IndexRoute,
  LoginRoute,
  RegisterRoute,
  AppRoute.addChildren([
    AppIndexRoute,
    AppCalendarRoute,
    AppSettingsRoute,
  ]),
]);

export { routeTree };
